### ISSUE TITLE
[Feature Request] Add support for Net Framework 4.8

### ISSUE THREAD

**Issue by fifuente** [mattwar/Kusto.Toolkit#12]
## [Feature Request] Add support for Net Framework

Right now, the package can only be consumed in .Net 6. Would like to have it available for .Net Framework projects as well.

I've cloned the repo to see the issues related to supporting net framework 4.8 and looks like it can be achieving to multi-target without a big change :)

Let me know if I can be of help here!

**Comment by mattwar** [comment]
I've added two new target frameworks net472 and netstandard20 to version 1.3.1.   Let me know if this works for you.

**Comment by fifuente** [comment]
@mattwar that seemed to have worked. Thanks for the quick addition!
