### ISSUE TITLE
[Feature Request] Add support to execute in a 64 bit environment

### ISSUE THREAD

**Issue by fifuente** [mattwar/Kusto.Toolkit#13]
Right now, when executing the following line of code, the process crashes.

``` cs
return await cacheSymbolLoader.AddOrUpdateDefaultDatabaseAsync(GlobalState.Default, dbName).ConfigureAwait(false);
```

My suspect is because I'm running my process in a 64-bit environment to simulate how it would run in an Azure Function. When I was doing my testing for this specific library, I made everything as a 32-bit environment, but when I wanted to simulate the complete workflow in my application, it crashed, and I wasn't able to catch any exception from code.

The reason I need to run this in a 64-bit env is because of other libraries that only support running in 64-bits, and when testing the application again in a 32-bit environment, then I was able to get the correct global state for the Kusto database.

Wondering if there is a bug of if it needs to support 64-bit env.

As an extra note, I was able to use the KustoCode library in a 64-bit environment, so it may be related to a new added library of the Kusto.Toolkit library.

**Comment by mattwar** [comment]
This library is only ever tested in a 64 bit environment.

**Comment by fifuente** [comment]
Interesting. I'll test it out again and get back to you with results or more details.
Thanks!

**Comment by fifuente** [comment]
Seems to be working after handling a deadlock occurring when calling AddOrUpdateDefaultDatabaseAsync. This was silently failing so I had to add the following fix to force it to run it synchronous.

```cs
            return Task.Run(async delegate
            {
                return await cacheSymbolLoader.AddOrUpdateDefaultDatabaseAsync(GlobalState.Default, dbName);
            }).GetAwaiter().GetResult();
```
