### ISSUE TITLE
bool fields are incorrectly interpreted as int by SymbolServerLoader.AddOrUpdateDefaultDatabaseAsync()

### ISSUE THREAD

**Issue by jkindwall** [mattwar/Kusto.Toolkit#20]
The code that we are using to generate the GlobalState object is as follows:

``` csharp
            ServerSymbolLoader symbolLoader = new(kustoSettings.ToKustoConnectionStringBuilder());
            this.KustoGlobalState =
                await symbolLoader.AddOrUpdateDefaultDatabaseAsync(GlobalState.Default, kustoSettings.DatabaseName);
```

Here is a screenshot of one of the tables in our database.
![ParseAndAnalyze_Bool](https://github.com/mattwar/Kusto.Toolkit/assets/2964211/5f00e9da-0cc1-4ca1-bd36-7b8680be06ef)

And here is a screenshot looking at the corresponding TableSymbol object for that table in the Visual Studio debugger.
![ParseAndAnalyze_NoBool](https://github.com/mattwar/Kusto.Toolkit/assets/2964211/edf47275-89df-40aa-b52e-0636b680b996)

Notice the "Enabled" field is typed as a bool in the original database, but it is defined as an int in the TableSymbol.

**Comment by mattwar** [comment]
Can you share the .create table command you used to create the table?

**Comment by mattwar** [comment]
Can you try updating to version 1.6.0 and see if that helps?

**Comment by jkindwall** [comment]
Just tried it on version 1.6.0, and it seems to be fixed in that version.  Thanks.
