### ISSUE TITLE
ServerSymbolLoader hangs indefinitely

### ISSUE THREAD

**Issue by tjohnson314** [mattwar/Kusto.Toolkit#29]
I'm using the following snippet of code to load symbols for my database:
```
var globals = GlobalState.Default;
var loader = new ServerSymbolLoader(connectionString);
var globalState = await loader.AddOrUpdateDefaultDatabaseAsync(globals, databaseName);
```
But the final step waits indefinitely. I can see that the first query was submitted:
```
.show databases | where DatabaseName == '<databaseName>' or PrettyName == '<databaseName>'
```
But I can't see anything else happening after that.

I tried running the query myself, and I see that it returns a column SuspensionState that is not present in ShowDatabasesResult. Maybe that's causing the issue?

**Comment by mattwar** [comment]
There was a few missing ConfigureAwait calls.  These have been fixed in 1.7.6
